import uuid
import difflib
import time
from typing import Optional, Dict, Any, List
from pydantic import BaseModel, Field, ConfigDict

from core.common.models import Diagnostic, Classification
from services.ai.strategies import STRATEGY_MAP, RemediationStrategy, ContextManagerStrategy
from services.ai.validator import PatchValidator, ValidationReport


class PatchResult(BaseModel):
    patch_id: str
    finding_id: str
    strategy: str
    explanation: str
    candidate_code: str = ""
    unified_diff: str = ""
    confidence: float = 0.95
    verification_status: str = "REJECTED"  # "VERIFIED_FIX", "REJECTED"
    is_verified: bool = False
    before_findings: int = 1
    after_findings: int = 0
    rejected_reason: Optional[str] = None
    verification_steps: List[str] = Field(default_factory=list)

    model_config = ConfigDict(arbitrary_types_allowed=True)


class AutoFixerEngine:
    """Automated Remediation Engine with Strategy Selection & Isolated Deterministic Verification."""

    def __init__(self, validator: Optional[PatchValidator] = None) -> None:
        self.validator = validator or PatchValidator()

    def generate_and_verify(
        self,
        source_code: str,
        diagnostic: Diagnostic,
        strategy_name: str = "context-manager",
        file_name: str = "target_module.py",
    ) -> PatchResult:
        patch_id = f"patch_{uuid.uuid4().hex[:10]}"
        strategy = STRATEGY_MAP.get(strategy_name.lower(), ContextManagerStrategy())

        # 1. Apply selected strategy
        candidate_code, explanation = strategy.apply(source_code, diagnostic)

        # Compute Unified Diff
        diff_lines = list(
            difflib.unified_diff(
                source_code.splitlines(keepends=True),
                candidate_code.splitlines(keepends=True),
                fromfile=f"a/{file_name}",
                tofile=f"b/{file_name}",
            )
        )
        unified_diff = "".join(diff_lines)

        if not unified_diff.strip():
            return PatchResult(
                patch_id=patch_id,
                finding_id=diagnostic.finding_id,
                strategy=strategy.strategy_name,
                explanation="No code changes generated by strategy.",
                candidate_code=source_code,
                unified_diff="",
                confidence=0.0,
                verification_status="REJECTED",
                is_verified=False,
                before_findings=1,
                after_findings=1,
                rejected_reason="Strategy produced no diff.",
            )

        # 2. Run Isolated Deterministic Validation via LeakGuard Analysis Engine
        report: ValidationReport = self.validator.validate_patch(
            original_source=source_code,
            candidate_source=candidate_code,
            target_diagnostic=diagnostic,
            file_name=file_name,
        )

        is_ver = report.is_valid
        ver_status = "VERIFIED_FIX" if is_ver else "REJECTED"
        rej_reason = None if is_ver else report.failure_reason

        return PatchResult(
            patch_id=patch_id,
            finding_id=diagnostic.finding_id,
            strategy=strategy.strategy_name,
            explanation=explanation,
            candidate_code=candidate_code,
            unified_diff=unified_diff,
            confidence=0.95 if is_ver else 0.20,
            verification_status=ver_status,
            is_verified=is_ver,
            before_findings=1,
            after_findings=report.new_findings_count if not report.original_finding_cleared else report.new_findings_count,
            rejected_reason=rej_reason,
            verification_steps=report.validation_steps,
        )
